spring:
  application:
    name: liquibase
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bendb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    changeLog: classpath:db/db.changelog-master.yml
    enabled: true
