server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"

# RabbitMQ connection details
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
