version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
