server:
  port: 9191
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination:
            kafka-input
        output:
          destination:
            kafka-output
