server:
  port: 9191
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input-channel:
          destination: kafka-input
        output-channel:
          destination: kafka-output
